#!/usr/bin/env bash

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
xinput set-prop 11 373 1837, 0, 0, 0, 0, 0, 0, 0
brightnessctl -d "intel_backlight" set 20%

pipewire &
nitrogen --restore &
picom &
nm-applet &
blueman-applet &
/home/malcolm/scripts/low_power_notify.sh &
/home/malcolm/scripts/volume-change.sh - 100
echo 0 > /tmp/volume

if grep "^NAME=" /etc/os-release | grep "NixOS"; then
    polybar bar2 &
else
    polybar bar1 &
fi

bspc monitor -d I II III IV V VI 
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           5
bspc config focused_border_color "#8ABEB7"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#RULES
bspc rule -a Blueman-manager state=floating rectangle=640x480+1200+80
